### ISSUE TITLE
EDNA mxv[1,2] strategy does not work with e.g. 5 images at 0, 45, ..., 180

### ISSUE THREAD

**Issue by graeme-winter** [edna-site/edna#26]
Due to the way that the indexing works with LABELIT; first last image used; would be better to use all of the images so getting wider coverage of reciprocal space. Do this by opening file in working directory for labelit.index dataset_preferences.py containing record

wedgelimit=%d

where %d == #images to be used in the analysis, therefore e.g. 

thau_1_0001.cbf
thau_1_0002.cbf
thau_1_0003.cbf
thau_1_0004.cbf
thau_1_0005.cbf

wedgelimit=5

would work

I attach example images where using 1, 5 current EDNA default will not work, 1..5 works very nicely.
[thau_1.zip](https://github.com/edna-site/edna/files/240011/thau_1.zip) contains images 1...5 in this example.

Code to modify is in /mxv1/plugins/EDPluginControlIndexing-v1.0/plugins/EDPluginControlIndexingLabelitv10.py

**Comment by graeme-winter** [comment]
Mathematically what is happening is that the curvature of reciprocal space is not sufficient to give third direction information when you have 0, 180 degree images with low resolution; also the spots in reciprocal space map onto nearly but not quite the same places => this messes with the max cell estimation. Corner case to consider is if the images passed are continuous e.g. 0-2 degrees @ 0.5 / frame - these will cause labelit to crash since the max cell is not passed; this is however a failure mode for the current implementation and not something I think you need to consider anyway.

**Comment by graeme-winter** [comment]
This happens if you give continuous images:

[gw56@ws133 edna]$ labelit.index /dls/i03/data/2016/cm14451-2/20160427/gw/test-pia/1/thaum_3_000[1-5].cbf
InputFileError: Input error: Indexing unlikely to succeed with wedge separation 0.050000

**Comment by olofsvensson** [comment]
Thanks a lot for this info, Graeme! I have committed a patch to the https://github.com/olofsvensson/edna-mx repository which enables Labelit to index more than two images.
